[tools]
# Language
"npm:typescript" = "5.9.3"
deno = "2.6.6"
go = "1.25.6"
lua-language-server = "3.17.1"
node = "25.5.0"
python = "3.14.2"
ruby = "4.0.1"
rust = "nightly"

"go:golang.org/x/tools/gopls" = "0.21.0"
"npm:@biomejs/biome" = "2.3.13"
"npm:@fsouza/prettierd" = "0.26.2"
"npm:@github/copilot-language-server" = "1.418.0"
"npm:@tailwindcss/language-server" = "0.14.29"
"npm:@vlabo/cspell-lsp" = "1.1.5"
"npm:css-variables-language-server" = "2.8.3"
"npm:cssmodules-language-server" = "1.5.2"
"npm:eslint_d" = "14.3.0"
"npm:oxlint" = "1.42.0"
"npm:prettier" = "3.8.1"
"npm:pyright" = "1.1.403"
"npm:stylelint-lsp" = "2.0.1"
"npm:typescript-language-server" = "5.1.3"
"npm:vscode-langservers-extracted" = "4.10.0"     # html,css,json,eslint,
"npm:yaml-language-server" = "1.19.2"
golangci-lint = "2.8.0"
ruff = "0.14.9"
stylua = "2.3.1"
shfmt = "latest"

# CLI tools (主に Homebrew で入れられないもの)
"cargo:https://github.com/itsjunetime/tdf.git" = "latest"
"cargo:https://github.com/skanehira/ghost.git" = "latest"
"cargo:https://github.com/ushironoko/octorus.git" = "latest"
"go:github.com/k1LoW/git-wt" = { version = "latest" }
"go:github.com/nametake/golangci-lint-langserver" = { version = "latest" }
"go:github.com/rhysd/vim-startuptime" = { version = "latest" }
"go:github.com/satococoa/wtp/v2/cmd/wtp" = { version = "latest" }
"npm:@github/copilot" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:@taplo/cli" = "latest"
"npm:agent-browser" = "latest"
"npm:zenn-cli" = "latest"
watchexec = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]
