# https://starship.rs/ja-jp/config/

format = """
$directory\
$git_branch\
$line_break\
$character"""

[character]
success_symbol = "[>](bold green) "
error_symbol = "[✗](bold red) "

[directory]
truncation_length = 5
truncation_symbol = "…/"
read_only = " "

[git_branch]
format = "[$symbol$branch]($style) "
truncation_length = 32
truncation_symbol = "…"
symbol = ""
